In [1]:
import pandas as pd
import numpy as np
import sklearn

In [87]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/housing_data_08-02-2021.csv')
df.head()

,location,district,rooms,size,level,max_levels,price
0,"город Ташкент, Юнусабадский район, Юнусабад 8-...",Юнусабадский,3,57,4,4,52000
1,"город Ташкент, Яккасарайский район, 1-й тупик ...",Яккасарайский,2,52,4,5,56000
2,"город Ташкент, Чиланзарский район, Чиланзар 2-...",Чиланзарский,2,42,4,4,37000
3,"город Ташкент, Чиланзарский район, Чиланзар 9-...",Чиланзарский,3,65,1,4,49500
4,"город Ташкент, Чиланзарский район, площадь Актепа",Чиланзарский,3,70,3,5,55000

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7565 entries, 0 to 7564
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    7565 non-null   object
 1   district    7565 non-null   object
 2   rooms       7565 non-null   int64
 3   size        7565 non-null   object
 4   level       7565 non-null   int64
 5   max_levels  7565 non-null   int64
 6   price       7565 non-null   object
dtypes: int64(3), object(4)
memory usage: 413.8+ KB

In [88]:
df.describe()

             rooms        level   max_levels
count  7565.000000  7565.000000  7565.000000
mean      2.625644     3.699273     6.038202
std       1.085201     2.237275     2.613271
min       1.000000     1.000000     1.000000
25%       2.000000     2.000000     4.000000
50%       3.000000     3.000000     5.000000
75%       3.000000     5.000000     9.000000
max      10.000000    19.000000    25.000000

In [92]:
df = df[(df['size'] < 500) & (df['price'] < 1000000) ]
df.describe()

             rooms         size        level   max_levels          price
count  7445.000000  7445.000000  7445.000000  7445.000000    7445.000000
mean      2.620551    73.095635     3.696038     6.027938   59035.582942
std       1.081142    37.309865     2.237723     2.607809   46728.531198
min       1.000000     1.000000     1.000000     1.000000       2.000000
25%       2.000000    50.000000     2.000000     4.000000   35000.000000
50%       3.000000    65.000000     3.000000     5.000000   46000.000000
75%       3.000000    85.000000     5.000000     9.000000   66500.000000
max      10.000000   456.000000    19.000000    25.000000  800000.000000

In [91]:
#for size column
df['size'] = pd.to_numeric(df['size'], errors='coerce')
df.dropna(subset=['size'], inplace=True)
df['size'] = df['size'].round()
df['size'] = df['size'].astype('int64')
#for price column
df['price'] = pd.to_numeric(df['price'], errors='coerce')
df.dropna(subset=['price'], inplace=True)
df['price'] = df['price'].astype('int64')
#see changes
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7465 entries, 0 to 7564
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    7465 non-null   object
 1   district    7465 non-null   object
 2   rooms       7465 non-null   int64
 3   size        7465 non-null   int64
 4   level       7465 non-null   int64
 5   max_levels  7465 non-null   int64
 6   price       7465 non-null   int64
dtypes: int64(5), object(2)
memory usage: 466.6+ KB

In [93]:
from sklearn.model_selection import train_test_split
train_set,test_set=train_test_split(df,test_size=0.2,random_state=50)

In [94]:
housing=train_set.drop(['price','location'],axis=1)
housing_labels = train_set['price'].copy()

In [95]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5956 entries, 5271 to 5896
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   district    5956 non-null   object
 1   rooms       5956 non-null   int64
 2   size        5956 non-null   int64
 3   level       5956 non-null   int64
 4   max_levels  5956 non-null   int64
dtypes: int64(4), object(1)
memory usage: 279.2+ KB

In [96]:
housing.head()

               district  rooms  size  level  max_levels
5271       Чиланзарский      2    48      1           4
1019       Чиланзарский      1    40      3           4
6547        Яшнободский      2    53      3           6
5884       Юнусабадский      3    60      3           3
2968  Мирзо-Улугбекский      5   200      1           5

In [97]:
housing_onehot = pd.get_dummies(housing['district']).astype(int)
housing_onehot

,Бектемирский,Мирабадский,Мирзо-Улугбекский,Олмазорский,Сергелийский,Учтепинский,Чиланзарский,Шайхантахурский,Юнусабадский,Яккасарайский,Янгихаётский,Яшнободский
5271,0,0,0,0,0,0,1,0,0,0,0,0
1019,0,0,0,0,0,0,1,0,0,0,0,0
6547,0,0,0,0,0,0,0,0,0,0,0,1
5884,0,0,0,0,0,0,0,0,1,0,0,0
2968,0,0,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2042,0,0,1,0,0,0,0,0,0,0,0,0
6345,0,0,0,0,0,1,0,0,0,0,0,0
1957,0,0,0,0,0,0,0,0,1,0,0,0
5684,0,0,1,0,0,0,0,0,0,0,0,0
5896,0,0,0,0,0,0,1,0,0,0,0,0

In [98]:
housing = housing.drop('district', axis=1)
housing = pd.concat([housing, housing_onehot], axis=1)

In [99]:
housing.head()

,rooms,size,level,max_levels,Бектемирский,Мирабадский,Мирзо-Улугбекский,Олмазорский,Сергелийский,Учтепинский,Чиланзарский,Шайхантахурский,Юнусабадский,Яккасарайский,Янгихаётский,Яшнободский
5271,2,48,1,4,0,0,0,0,0,0,1,0,0,0,0,0
1019,1,40,3,4,0,0,0,0,0,0,1,0,0,0,0,0
6547,2,53,3,6,0,0,0,0,0,0,0,0,0,0,0,1
5884,3,60,3,3,0,0,0,0,0,0,0,0,1,0,0,0
2968,5,200,1,5,0,0,1,0,0,0,0,0,0,0,0,0

In [100]:
from sklearn.base import BaseEstimator, TransformerMixin
rooms_ix, size_ix = 0, 1
class CombinedAttributes(BaseEstimator, TransformerMixin):
    def __init__(self, add_size_per_room=True):
        self.add_size_per_room = add_size_per_room
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        rooms_per_size = X[:, size_ix] / X[:, rooms_ix]
        if self.add_size_per_room:
            return np.c_[X, rooms_per_size]
        else:
            return X

In [101]:
attr_adder = CombinedAttributes()
housing_extra_attribs = attr_adder.transform(housing.values)

In [102]:
housing_extra_attribs[0,:]

array([ 2., 48.,  1.,  4.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0., 24.])

In [103]:
housing_extra_attribs = attr_adder.transform(housing.values)
housing.insert(4, 'size_per_room', housing_extra_attribs[:, -1])

In [104]:
housing.head()

,rooms,size,level,max_levels,size_per_room,Бектемирский,Мирабадский,Мирзо-Улугбекский,Олмазорский,Сергелийский,Учтепинский,Чиланзарский,Шайхантахурский,Юнусабадский,Яккасарайский,Янгихаётский,Яшнободский
5271,2,48,1,4,24.0,0,0,0,0,0,0,1,0,0,0,0,0
1019,1,40,3,4,40.0,0,0,0,0,0,0,1,0,0,0,0,0
6547,2,53,3,6,26.5,0,0,0,0,0,0,0,0,0,0,0,1
5884,3,60,3,3,20.0,0,0,0,0,0,0,0,0,1,0,0,0
2968,5,200,1,5,40.0,0,0,1,0,0,0,0,0,0,0,0,0

In [105]:
housing.describe()

,rooms,size,level,max_levels,size_per_room,Бектемирский,Мирабадский,Мирзо-Улугбекский,Олмазорский,Сергелийский,Учтепинский,Чиланзарский,Шайхантахурский,Юнусабадский,Яккасарайский,Янгихаётский,Яшнободский
count,5956.000000,5956.000000,5956.000000,5956.000000,5956.000000,5956.000000,5956.000000,5956.000000,5956.000000,5956.000000,5956.000000,5956.000000,5956.000000,5956.000000,5956.000000,5956.000000,5956.000000
mean,2.626763,73.152955,3.692579,6.030557,28.549623,0.000839,0.103593,0.182337,0.035762,0.021995,0.119040,0.215245,0.051377,0.118200,0.085460,0.002015,0.064137
std,1.072775,36.586774,2.239262,2.618427,7.715866,0.028964,0.304757,0.386155,0.185712,0.146678,0.323862,0.411027,0.220784,0.322872,0.279589,0.044845,0.245017
min,1.000000,1.000000,1.000000,1.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,50.000000,2.000000,4.000000,23.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.000000,66.000000,3.000000,5.000000,26.666667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3.000000,85.000000,5.000000,9.000000,31.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,10.000000,456.000000,19.000000,25.000000,114.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [106]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()
min_max_scaler.fit_transform(housing)

array([[0.11111111, 0.1032967 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.08571429, 0.11111111, ..., 0.        , 0.        ,
        0.        ],
       [0.11111111, 0.11428571, 0.11111111, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.11111111, 0.14065934, 0.11111111, ..., 0.        , 0.        ,
        0.        ],
       [0.22222222, 0.18021978, 0.05555556, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.07472527, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [107]:
housing

,rooms,size,level,max_levels,size_per_room,Бектемирский,Мирабадский,Мирзо-Улугбекский,Олмазорский,Сергелийский,Учтепинский,Чиланзарский,Шайхантахурский,Юнусабадский,Яккасарайский,Янгихаётский,Яшнободский
5271,2,48,1,4,24.000000,0,0,0,0,0,0,1,0,0,0,0,0
1019,1,40,3,4,40.000000,0,0,0,0,0,0,1,0,0,0,0,0
6547,2,53,3,6,26.500000,0,0,0,0,0,0,0,0,0,0,0,1
5884,3,60,3,3,20.000000,0,0,0,0,0,0,0,0,1,0,0,0
2968,5,200,1,5,40.000000,0,0,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2042,2,57,5,5,28.500000,0,0,1,0,0,0,0,0,0,0,0,0
6345,1,33,3,4,33.000000,0,0,0,0,0,1,0,0,0,0,0,0
1957,2,65,3,4,32.500000,0,0,0,0,0,0,0,0,1,0,0,0
5684,3,83,2,8,27.666667,0,0,1,0,0,0,0,0,0,0,0,0
5896,1,35,1,4,35.000000,0,0,0,0,0,0,1,0,0,0,0,0