# Tashkent House Price Prediction - Data Cleaning

## Objective
The goal of this notebook is to clean the raw dataset by handling missing values,
fixing data types, and preparing the dataset for further analysis.

In [3]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv(r'C:\Users\Farruxbek\Downloads\housing_data_08-02-2021.csv')
df.head()

,location,district,rooms,size,level,max_levels,price
0,"город Ташкент, Юнусабадский район, Юнусабад 8-...",Юнусабадский,3,57,4,4,52000
1,"город Ташкент, Яккасарайский район, 1-й тупик ...",Яккасарайский,2,52,4,5,56000
2,"город Ташкент, Чиланзарский район, Чиланзар 2-...",Чиланзарский,2,42,4,4,37000
3,"город Ташкент, Чиланзарский район, Чиланзар 9-...",Чиланзарский,3,65,1,4,49500
4,"город Ташкент, Чиланзарский район, площадь Актепа",Чиланзарский,3,70,3,5,55000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7565 entries, 0 to 7564
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    7565 non-null   object
 1   district    7565 non-null   object
 2   rooms       7565 non-null   int64
 3   size        7565 non-null   object
 4   level       7565 non-null   int64
 5   max_levels  7565 non-null   int64
 6   price       7565 non-null   object
dtypes: int64(3), object(4)
memory usage: 413.8+ KB

In [17]:
df.describe()

             rooms        level   max_levels
count  7565.000000  7565.000000  7565.000000
mean      2.625644     3.699273     6.038202
std       1.085201     2.237275     2.613271
min       1.000000     1.000000     1.000000
25%       2.000000     2.000000     4.000000
50%       3.000000     3.000000     5.000000
75%       3.000000     5.000000     9.000000
max      10.000000    19.000000    25.000000

In [20]:
df['size'].unique()

array(['57', '52', '42', '65', '70', '28', '30', '32', '51', '67', '35',
       '43', '90', '80', '69', '96', '76', '45', '27', '64', '26', '72',
       '100', '63', '48', '102', '78', '34', '56', '98', '93', '60', '82',
       '120', '110', '95', '68', '46', '40', '53', '54', '20', '50', '36',
       '58', '74', '94', '85', '125', '64.67', '22', '66', '37', '61',
       '69.65', '88', '38', '55.13', '91', '111', '107', '62', '40.41',
       '75', '84', '117', '47', '33', '187', '29', '11', '122', '119',
       '164', '92', '55', '89', '208', '44', '86', '150', '56.10', '83',
       '49', '142', '115', '350', '81', '89.55', '59', '145', '116', '77',
       '24', '41', '255', '266', '210', '55.62', '140', '141', '60.94',
       '165', '215', '66.82', '128', '97', '130', '105', '137', '47.14',
       '71', '160', '118', '152', '21', '104', '180', '109', '135', '73',
       '39', '39.11', '157', '112', '93.22', '106', '214', '235', '16',
       '300', '57.95', '79', '5', '53.06', '62.50', '92.50', '203',
       '113.60', '246', '87.05', '121', '99', '87.65', '129.14', '108.27',
       '18', '103', '7359', '196', '134', '128.66', '97.30', '190',
       '65.80', '108', '124', '166', '236', '184', '17', '59.60', '78.27',
       '65.50', '48.36', '138', '41.37', '183.50', '186', '114', '51.60',
       '25', '136', '206', '58.50', '280', '448', '1', '64.40', '248',
       '132', '113', '268', '58.41', '265', '91.62', '58.10', '82.57',
       '40.52', '68.40', '456', '330', '254', '252', '126', '155', '317',
       '131', '182', '400', '310', '45.82', '69.33', '101', '200', '183',
       '68.41', '105.60', '38.51', '8.50', '147', '24500', '31', '279',
       '19', '3', '23', '87', '347', '191', '153', '189', '42.16',
       '70000', '178', '225', '44.90', '72.50', '87.27', '161', '82.96',
       '14', '3448', '77.32', '67.53', '43.31', '173', '46.23', '188',
       '97.53', '55.47', '148', '360', '170', '44000', '43.50', '67.68',
       '58.90', '270', '49.44', '47.50', '50.30', '66.19', '51.33',
       '57.60', '176', '77.47', '46.70', '88.90', '49.88', '56.97',
       '129.18', '54.90', '86.60', '123', '217', '63.09', '77.50',
       '205.80', '336', '213', '52.19', '168', '12', '56.47', '29.70',
       '139', '282', '79.30', '95.13', '59.80', '154', '313', '260',
       '64.70', '87.71', '64.50', '120.30', '216', '49.30', '4', '500',
       '47.30', '47.20', '230', '26.40', '169', '69.80', '51.14', '23.80',
       '48.60', '198', '77.36', '177', '207', '127', '167', '321',
       '42.60', '27.70', '57.85', '90.18', '172', '232', '71.20', '69.46',
       '69000', '175', '290', '73.80', '43.90', '3.80', '250', '25.30',
       '131.40', '79.86', '23.70', '99.30', '40.20', '69.70', '90.54',
       '320', '41.50', '45.09', '60.70', '38.17', '37.29', '420',
       'Площадьземли:1сот', '146', '28.52', '67000', '149', '83.18',
       '56.80', '185', '77.60', '59.31', '151', '56.14', '58.80', '56.20',
       '75.80', '16.70', '66.40', '75.41', '30.50', '56.89', '76.12',
       '89.80', '58.60', '15', '76.87', '70.06', '133', '68.37', '61.91',
       '53.10', '39.90', '41.40', '52.50', '104.10', '240', '192',
       '49.50', '31.30', '46.30', '60.50', '37.60', '64.75', '99.50',
       '54.15', '60.89', '144', '39.38', '341', '93.60', '211', '38.70',
       '74.07', '7407', '163', '83.83', '100.26', '96.25', '76.54',
       '60.43', '57.74', '66.16', '2100', '53.35', '77.98', '58.30',
       '76.50', '36.64', '72.86', '27.50'], dtype=object)

In [19]:
df['price'].unique()

array(['52000', '56000', '37000', '49500', '55000', '25500', '21200',
       '20000', '26200', '22200', '24200', '30200', '22500', '32500',
       '45000', '47000', '49900', '76000', '65000', '47500', '30000',
       '32000', '44000', '56500', '35000', '23500', '60500', '68000',
       '41500', '52500', '43000', '80000', '42000', '23000', '88784',
       '97000', '28500', '34500', '51000', '48000', '40000', '67000',
       '40500', '54000', '36000', '63000', '63500', '70000', '91000',
       '83000', '19765', '50000', '86000', '31500', '26500', '14500',
       '27000', '59500', '47299', '38000', '29500', '61500', '46500',
       '58400', '26000', '105000', '53500', '12500', '107000', '39414',
       '60000', '49000', '18000', '42500', '45800', '24000', '58000',
       '55500', '31000', '41000', '50500', '13071', '45188', '53000',
       '25600', '35226', '36500', '142000', '85000', '110000', '69000',
       '28900', '34000', '25000', '39000', '125000', '28000', '43500',
       '39999', '24500', '210000', '7500', '95000', 'Договорная', '70500',
       '170000', '30500', '37500', '46000', '38500', '81772', '50533',
       '119000', '93000', '23800', '32900', '29800', '62000', '36999',
       '36200', '45500', '120000', '84000', '77000', '260000', '75000',
       '54900', '54500', '1000', '31300', '33500', '64500', '13075',
       '115000', '128000', '33000', '66000', '37700', '75500', '270000',
       '285000', '27500', '265000', '31507', '129999', '34997', '35500',
       '1666000', '73000', '37400', '35800', '100000', '56600', '36542',
       '264999', '259999', '34499', '87000', '78000', '150000', '98500',
       '81999', '22534', '57000', '64000', '54962', '20600', '68500',
       '40200', '21500', '31999', '134000', '102711', '33998', '64700',
       '85500', '29000', '39600', '160000', '133000', '71000', '92000',
       '140000', '36800', '74000', '22000', '61000', '44998', '35999',
       '55290', '38190', '20200', '23200', '35200', '25200', '13700',
       '14700', '44300', '38999', '64999', '235000', '38200', '79500',
       '98000', '82000', '28700', '335000', '124999', '164500', '44200',
       '90000', '146500', '29996', '26800', '24700', '23542', '59000',
       '126000', '103000', '102000', '82500', '21000', '78500', '96000',
       '380000', '59999', '31800', '34600', '29900', '395000', '425000',
       '20900', '135000', '19500', '31992', '99000', '52900', '39800',
       '51500', '108417', '72000', '29600', '128631', '18500', '127000',
       '98979', '58803', '23999', '119991', '169000', '62338', '75475',
       '20500', '44500', '60675', '39997', '68614', '92479', '190000',
       '77534', '39500', '119900', '165000', '35900', '54996', '42200',
       '89000', '34998', '77469', '67500', '92135', '17500', '73500',
       '130000', '55700', '48500', '200000', '139999', '77500', '65999',
       '113000', '74900', '104900', '37800', '141500', '64996', '33999',
       '175000', '43800', '59800', '94000', '19000', '12000', '15500',
       '68998', '22999', '88000', '50670', '132000', '49800', '57500',
       '51498', '31307', '204100', '83500', '24921', '118000', '26300',
       '123000', '42800', '203000', '16000', '74500', '33700', '76500',
       '66500', '250000', '205000', '155000', '106000', '39900', '23513',
       '118500', '320000', '425600', '220000', '387000', '145000',
       '29400', '32200', '44600', '22300', '23477', '198750', '25907',
       '58500', '195000', '230000', '280000', '800000', '40400', '55708',
       '44900', '69900', '3780000', '21600', '85999', '26700', '290000',
       '2000', '40795', '112000', '15714', '58999', '60800', '23600',
       '295000', '25408', '14800', '49200', '17000', '81000', '72500',
       '88308', '64505', '67997', '20800', '138000', '66445', '96096',
       '72944', '72750', '13067', '59849', '141922', '61692', '104000',
       '236000', '45474', '162000', '79000', '33776', '40858', '62500',
       '49999', '158000', '13500', '33505', '225000', '71800', '215000',
       '172000', '136500', '33800', '15000', '375000', '25700', '146000',
       '54998', '240000', '22800', '23501', '33200', '192000', '51999',
       '121861', '129000', '57997', '46600', '142500', '87500', '67998',
       '47400', '90999', '91998', '19335', '25800', '28200', '79900',
       '84500', '139500', '34700', '17700', '14000', '42900', '12498',
       '10600', '12300', '56001', '34800', '48600', '43999', '79999',
       '136000', '38499', '180000', '57700', '69999', '23400', '108000',
       '82999', '208000', '50562', '56700', '49994', '48499', '65500',
       '111000', '46200', '24300', '300000', '43200', '39150', '33600',
       '74970', '60700', '89999', '11000', '22907', '8000', '219000',
       '500000', '31501', '43998', '17200', '267000', '53089', '39700',
       '55800', '58800', '42100', '66455', '66847', '23990', '48900',
       '21660', '46835', '27598', '18332', '28481', '72356', '69724',
       '31622', '55710', '57853', '69620', '32999', '20110', '56491',
       '38282', '69780', '60260', '32245', '93128', '119562', '37197',
       '50633', '58583', '96421', '83257', '23641', '74280', '52148',
       '37292', '33903', '105805', '73999', '530000', '49600', '10000',
       '131500', '504000', '185000', '53999', '33539', '43524', '8999',
       '39985', '69990', '365000', '305000', '25400', '340000', '57993',
       '95600', '27700', '38448', '28100', '12100', '26100', '29999',
       '27288', '129500', '259000', '26499', '37410', '59990', '45200',
       '101564', '109989', '34996', '1800', '16500', '37751', '54600',
       '36998', '134500', '25150', '38700', '40100', '45370', '72898',
       '25499', '34200', '43700', '41744', '46700', '34400', '78800',
       '11500', '64600', '99900', '179000', '109000', '27300', '370000',
       '38600', '38663', '193000', '135500', '330000', '77501', '198000',
       '30800', '30299', '299000', '129900', '139900', '114900', '75900',
       '113500', '128500', '77999', '46999', '37900', '258001', '74999',
       '420000', '644000', '37200', '45700', '116000', '34555', '41700',
       '72222', '74200', '53700', '2864', '23700', '59900', '42967',
       '19800', '17871', '217000', '51998', '148000', '23900', '56980',
       '55200', '46900', '30300', '81500', '167000', '25990', '44800',
       '27200', '29200', '15682', '37002', '209000', '31080', '41498',
       '47700', '168000', '61900', '385000', '350000', '201493', '41200',
       '52991', '56900', '89050', '161000', '12800', '97500', '28800',
       '52000000', '22600', '18600', '255000', '28423', '10500', '43160',
       '38800', '29300', '25900', '34900', '26900', '1344000', '38900',
       '57200', '66200', '40300', '93500', '116001', '47300', '310000',
       '157550', '128780', '167200', '42108', '4240000', '50027', '34326',
       '21823', '27511', '22379', '42423', '84119', '61413', '14439',
       '34075', '42400', '60132', '77995', '53972', '50996', '24749',
       '13680', '19380', '21989', '182000', '58499', '154998', '61998',
       '72999', '27950', '35192', '22700', '92500', '15504000', '32300',
       '6630000', '27394', '26829', '18385', '122000', '61001', '196000',
       '31200', '2', '41999', '45999', '51600', '7300', '21800',
       '5568000', '8500', '2400', '96500', '35997', '13000', '34999',
       '1470000', '30554', '63999', '22914'], dtype=object)

In [22]:
# Convert to numeric (invalid - NaN)
df['size'] = pd.to_numeric(df['size'], errors='coerce')
df['price'] = pd.to_numeric(df['price'], errors='coerce')

In [23]:
# Fill missing values
df['size'] = df['size'].fillna(df['size'].median())
df['price'] = df['price'].fillna(df['price'].median())

In [24]:
# Remove unrealistic sizes  and prices
df = df[(df['size'] > 10) & (df['size'] < 500)]
df = df[(df['price'] > 10000) & (df['price'] < 500000)]

In [26]:
df.to_csv('../data/cleaned_data.csv', index=False)

## Conclusion

- Missing values have been handled
- Data types have been corrected
- Dataset is now clean and ready for exploratory data analysis