# Tashkent House Price Prediction - Feature Engineering

## Objective
The goal of this notebook is to create new features, remove irrelevant ones,
and prepare the dataset for machine learning models.

In [10]:
import pandas as pd
import numpy as np

In [12]:
# Load cleaned dataset
df = pd.read_csv('../data/cleaned_data.csv')

df.head()

,location,district,rooms,size,level,max_levels,price
0,"город Ташкент, Юнусабадский район, Юнусабад 8-...",Юнусабадский,3,57.0,4,4,52000.0
1,"город Ташкент, Яккасарайский район, 1-й тупик ...",Яккасарайский,2,52.0,4,5,56000.0
2,"город Ташкент, Чиланзарский район, Чиланзар 2-...",Чиланзарский,2,42.0,4,4,37000.0
3,"город Ташкент, Чиланзарский район, Чиланзар 9-...",Чиланзарский,3,65.0,1,4,49500.0
4,"город Ташкент, Чиланзарский район, площадь Актепа",Чиланзарский,3,70.0,3,5,55000.0

In [13]:
# Drop unnecessary columns
df = df.drop(columns=['location'], errors='ignore')

In [14]:
# Convert categorical variable into dummy variables
df = pd.get_dummies(df, columns=['district'], drop_first=True,dtype=int)

In [15]:
df.head()

,rooms,size,level,max_levels,price,district_Мирабадский,district_Мирзо-Улугбекский,district_Олмазорский,district_Сергелийский,district_Учтепинский,district_Чиланзарский,district_Шайхантахурский,district_Юнусабадский,district_Яккасарайский,district_Янгихаётский,district_Яшнободский
0,3,57.0,4,4,52000.0,0,0,0,0,0,0,0,1,0,0,0
1,2,52.0,4,5,56000.0,0,0,0,0,0,0,0,0,1,0,0
2,2,42.0,4,4,37000.0,0,0,0,0,0,1,0,0,0,0,0
3,3,65.0,1,4,49500.0,0,0,0,0,0,1,0,0,0,0,0
4,3,70.0,3,5,55000.0,0,0,0,0,0,1,0,0,0,0,0

In [22]:
# Define features and target
X = df.drop('price', axis=1)
Y = df['price']

In [25]:
X.head()

,rooms,size,level,max_levels,district_Мирабадский,district_Мирзо-Улугбекский,district_Олмазорский,district_Сергелийский,district_Учтепинский,district_Чиланзарский,district_Шайхантахурский,district_Юнусабадский,district_Яккасарайский,district_Янгихаётский,district_Яшнободский
0,3,57.0,4,4,0,0,0,0,0,0,0,1,0,0,0
1,2,52.0,4,5,0,0,0,0,0,0,0,0,1,0,0
2,2,42.0,4,4,0,0,0,0,0,1,0,0,0,0,0
3,3,65.0,1,4,0,0,0,0,0,1,0,0,0,0,0
4,3,70.0,3,5,0,0,0,0,0,1,0,0,0,0,0

In [26]:
Y.head()

0    52000.0
1    56000.0
2    37000.0
3    49500.0
4    55000.0
Name: price, dtype: float64

In [31]:
df.to_csv('../data/featured_data.csv', index=False)

## Conclusion

- Categorical variables were encoded
- Unnecessary columns were removed
- Data was split into features (X) and target (y)

The dataset is now ready for model training.